// ─── FACING BETS — situaciones nuevas ────────────────────────────────────────
// Añade aquí nuevas situaciones de tipo "facing" en lugar de editar el array
// FACING_SITUATIONS gigante dentro de grinders-manual.jsx.
// Mismo formato: { id, type:"facing", hand, board, street, open, ctx, pos, callPos,
//                   descEs, descEn, es, en }
// IDs sugeridos: a partir de 1900 (los existentes van 601-620).

// ── FACING BETS — Spots de Fin de Acción (Avanzado) — 1901-1920 ─────────────
// Conceptos avanzados: check-raises, min-raises, blockers, boards peligrosos,
// short stacks, lecturas de frecuencia/población, colores bajos en tableros
// de 4 a un palo, rangos "capados".
export const FACING_SITUATIONS_EXTRA = [

  // S1901: River check-raise tras 2 barriles, overpair → FOLD
  {id:1901,type:"facing",hand:"K♠ K♦",board:"Q♦8♣4♠2♥9♦",street:"river",open:false,
   ctx:"facing_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg (VPIP 27%, PFR 21%, Raise vs Bet River 3%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♦8♣4♠: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn 2♥: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 9♦: BB checkea. Hero apuesta 18BB (63% del bote). BB sube a 55BB.\nCoste del call: 37BB adicionales.",
   descEn:"NL25 · BTN vs BB · Reg (VPIP 27%, PFR 21%, Raise vs Bet River 3%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♦8♣4♠: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn 2♥: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 9♦: BB checks. Hero bets 18BB (63% of pot). BB raises to 55BB.\nCost of call: 37BB more.",
   es:"FOLD. KK (overpair) en Q-8-4-2-9 vs check-raise en el river. ER = 37/(37+101.5) ≈ 27%. Raise vs Bet River con una frecuencia de solo 3% es una de las acciones más polarizadas del póker — casi nunca es un farol contra un sizing tan grande. El rango de check-raise river de este reg aquí es básicamente sets (888, 444, 999), dos pares (Q9, Q8, 98) o straights con runners — KK pierde contra prácticamente todo eso. ER=27% parece bajo, pero tu equidad real vs ese rango polarizado es ~10%. Foldea un overpair que se siente fuerte pero ya no lo es.",
   en:"FOLD. KK (overpair) on Q-8-4-2-9 vs a river check-raise. ER = 37/(37+101.5) ≈ 27%. Raise vs Bet River at only a 3% frequency is one of the most polarized actions in poker — almost never a bluff against this sizing. This reg's river check-raise range here is basically sets (888, 444, 999), two pair (Q9, Q8, 98), or runner-runner straights — KK loses to almost all of it. ER=27% looks low, but your real equity vs that polarized range is ~10%. Fold an overpair that feels strong but no longer is."},

  // S1902: Ace-high con bloqueador de Ases vs triple barrel → CALL
  {id:1902,type:"facing",hand:"A♠ T♠",board:"K♥9♠4♦7♣2♠",street:"river",open:true,
   ctx:"facing_river",pos:"BB",callPos:"CO",
   descEs:"NL25 · BB vs CO · Reg (VPIP 24%, PFR 19%, CBet River 50%)\nPreflop: CO abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop K♥9♠4♦: Hero checkea. CO apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 7♣: Hero checkea. CO apuesta 8BB. Hero paga. Bote: 28.5BB.\nRiver 2♠: Hero checkea. CO apuesta 20BB (≈70% del bote).",
   descEn:"NL25 · BB vs CO · Reg (VPIP 24%, PFR 19%, CBet River 50%)\nPreflop: CO opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop K♥9♠4♦: Hero checks. CO bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 7♣: Hero checks. CO bets 8BB. Hero calls. Pot: 28.5BB.\nRiver 2♠: Hero checks. CO bets 20BB (≈70% of pot).",
   es:"PAGAR. AT no tiene ni pareja en K-9-4-7-2 — a primera vista parece un fold automático. ER = 20/(20+48.5) ≈ 29%. Pero tu A♠ es un BLOCKER clave: elimina las combinaciones de AA y AK del rango de valor de CO, que son precisamente las manos más probables para un triple barril en este tablero seco. Al quitar esas combinaciones de valor top, la proporción de farol (proyectos fallidos como QJ, JT, T9, 65, o draws de color que no llegaron) dentro del rango de apuesta de CO sube significativamente. AT le gana a todos esos faroles. Con bloqueador de Ases, el 29% de ER se vuelve alcanzable. Paga.",
   en:"CALL. AT has no pair on K-9-4-7-2 — at first glance this looks like an automatic fold. ER = 20/(20+48.5) ≈ 29%. But your A♠ is a key BLOCKER: it removes AA and AK combos from CO's value range, exactly the most likely hands for a triple barrel on this dry board. Removing those top value combos significantly raises the proportion of bluffs (missed draws like QJ, JT, T9, 65, or busted flush draws) within CO's betting range. AT beats all of those bluffs. With the Ace blocker, the 29% ER becomes reachable. Call."},

  // S1903: Dos pares "top" demotadas por river que empareja, all-in → FOLD
  {id:1903,type:"facing",hand:"A♦ K♦",board:"A♠K♣7♦7♥3♣",street:"river",open:false,
   ctx:"facing_allin",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg (VPIP 28%, PFR 22%) · All-in en el river\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop A♠K♣7♦: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn 7♥ (el tablero empareja): BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 3♣: BB va all-in por 74BB. Bote total si pagas: 176.5BB. Coste del call: 74BB.",
   descEn:"NL25 · BTN vs BB · Reg (VPIP 28%, PFR 22%) · All-in on river\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop A♠K♣7♦: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn 7♥ (board pairs): BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 3♣: BB goes all-in for 74BB. Total pot if you call: 176.5BB. Cost of call: 74BB.",
   es:"FOLD. AK te da dos pares (Ases y Reyes) en A-K-7-7-3 — parece tu mejor par posible, pero el momento en que el tablero EMPAREJÓ (7-7) cambió todo: cualquier 7 en la mano del rival hace full house (777 + AA o KK), y cualquier AA o KK en su mano también hace full house, ambos superando tus dos pares. ER = 74/(74+176.5) ≈ 30%, pero tu equidad real vs el rango de shove de BB en este river es ~15-18%. La línea de BB (call-call-shove en un tablero estático que de repente se empareja) encaja con manos que ya tenían un 7, AA o KK desde antes y ahora tienen un monstruo. Tus 'dos pares top' fueron degradados a bluff catcher en el instante en que cayó el segundo 7. Foldea.",
   en:"FOLD. AK gives you two pair (Aces and Kings) on A-K-7-7-3 — looks like your best possible two pair, but the moment the board PAIRED (7-7) everything changed: any 7 in villain's hand makes a full house (777 + AA or KK), and any AA or KK in their hand also makes a full house, both beating your two pair. ER = 74/(74+176.5) ≈ 30%, but your real equity vs BB's shoving range on this river is ~15-18%. BB's line (call-call-shove on a static board that suddenly pairs) fits hands that already had a 7, AA, or KK and now have a monster. Your 'top two pair' got demoted to a bluff catcher the instant the second 7 hit. Fold."},

  // S1904: Min-raise river — tell de población, TPTK → FOLD
  {id:1904,type:"facing",hand:"A♠ Q♠",board:"A♣T♦4♥7♣2♦",street:"river",open:false,
   ctx:"facing_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Reg (VPIP 25%, PFR 19%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop A♣T♦4♥: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn 7♣: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 2♦: BB checkea. Hero apuesta 18BB (≈63% del bote). BB sube (min-raise) a 36BB.\nCoste del call: 18BB adicionales.",
   descEn:"NL25 · CO vs BB · Reg (VPIP 25%, PFR 19%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop A♣T♦4♥: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn 7♣: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 2♦: BB checks. Hero bets 18BB (≈63% of pot). BB raises (min-raise) to 36BB.\nCost of call: 18BB more.",
   es:"FOLD. AQ (TPTK) en A-T-4-7-2, apostando valor las 3 calles, recibe un MIN-RAISE en el river. ER = 18/(18+100.5) ≈ 18% — matemáticamente trivial. Pero el min-raise de río en NL25 es una de las señales de población MÁS fuertes que existen: casi ningún jugador min-raisea como farol (arriesga poco extra para ganar poco, con pésima relación riesgo/fold-equity comparado con un raise grande o un shove). Un min-raise representa casi siempre a un jugador que TEME no recibir más acción con una mano muy fuerte: dos pares, sets, tríos rivereados (44, 77, A4, A7, 47, 74) o straights con K. Aunque el ER diga 18%, tu equidad real vs un rango ~95% valor es cercana a 0%. Esto es el clásico spot donde las pot odds mienten — foldea al min-raise.",
   en:"FOLD. AQ (TPTK) on A-T-4-7-2, value-betting all 3 streets, gets MIN-RAISED on the river. ER = 18/(18+100.5) ≈ 18% — mathematically trivial. But a river min-raise in NL25 is one of the strongest population reads that exists: almost no one min-raises as a bluff (risking a little extra to win a little, with terrible risk-to-fold-equity ratio compared to a bigger raise or a shove). A min-raise almost always represents a player AFRAID of not getting more action with a very strong hand: two pair, sets, rivered trips (44, 77, A4, A7, 47, 74), or straights with a K. Even though ER says 18%, your real equity vs a ~95% value range is near 0%. This is the classic spot where pot odds lie — fold to the min-raise."},

  // S1905: Thin call vs blocking bet pequeño en river → CALL
  {id:1905,type:"facing",hand:"A♣ T♣",board:"A♦8♣3♠5♥J♦",street:"river",open:true,
   ctx:"facing_river",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Fish pasivo (VPIP 51%, PFR 8%, CBet River 22%)\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop A♦8♣3♠: Hero checkea. BTN apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 5♥: Hero checkea. BTN checkea. Bote: 12.5BB.\nRiver J♦: Hero checkea. BTN apuesta 3BB (≈24% del bote — blocking bet).",
   descEn:"NL25 · BB vs BTN · Passive fish (VPIP 51%, PFR 8%, CBet River 22%)\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop A♦8♣3♠: Hero checks. BTN bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 5♥: Hero checks. BTN checks. Pot: 12.5BB.\nRiver J♦: Hero checks. BTN bets 3BB (≈24% of pot — blocking bet).",
   es:"PAGAR (call thin). AT (top pair, kicker decente) en A-8-3-5-J. ER = 3/(3+15.5) ≈ 16%. BTN checkeó el turn y ahora apuesta un tamaño diminuto (24% del bote) en el river — esto es una 'blocking bet' clásica. La población en NL25 usa apuestas pequeñas de río tras checkear el turn casi exclusivamente para llegar barato al showdown con manos medias (un As peor, una pareja de Js, etc.), no para sacar valor de manos fuertes (que apostarían 60-80%+) ni para farolear (que también suelen sizear más grande o simplemente checkear). AT le gana a la mayoría de esas manos medias. Con un ER de solo 16%, este call es trivial. Paga.",
   en:"CALL (thin call). AT (top pair, decent kicker) on A-8-3-5-J. ER = 3/(3+15.5) ≈ 16%. BTN checked the turn and now bets a tiny size (24% of pot) on the river — this is a classic 'blocking bet'. NL25 population uses small river bets after checking the turn almost exclusively to get to a cheap showdown with medium-strength hands (a worse Ace, a pair of jacks, etc.), not to extract value from strong hands (which would bet 60-80%+) or to bluff (which also tends to size up, or just check). AT beats most of those medium hands. With an ER of only 16%, this call is trivial. Call."},

  // S1906: Combo draw vs shove de short stack en turn → CALL
  {id:1906,type:"facing",hand:"J♥ T♥",board:"9♥8♠2♥4♣",street:"turn",open:true,
   ctx:"facing_allin",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB (short stack, 35BB) · All-in en el turn\nPreflop: Hero abre BTN 2.5BB. BB (35BB) paga. Bote: 5.5BB.\nFlop 9♥8♠2♥: BB checkea. Hero apuesta 3.5BB. BB paga (combo draw). Bote: 12.5BB.\nTurn 4♣: BB va all-in por 28.5BB. Bote total si pagas: 41BB. Coste del call: 28.5BB.",
   descEn:"NL25 · BTN vs BB (short stack, 35BB) · All-in on turn\nPreflop: Hero opens BTN 2.5BB. BB (35BB) calls. Pot: 5.5BB.\nFlop 9♥8♠2♥: BB checks. Hero bets 3.5BB. BB calls (combo draw). Pot: 12.5BB.\nTurn 4♣: BB goes all-in for 28.5BB. Total pot if you call: 41BB. Cost of call: 28.5BB.",
   es:"PAGAR. J♥T♥ en 9♥8♠2♥4♣: tienes flush draw de corazones (9 outs) + OESD (J-T-9-8, completa con Q o 7) — descontando solapamientos (Q♥ y 7♥ ya cuentan como outs de color), el total es ≈ 15 outs limpios = ~32-35% de equidad pura por sí sola. ER = 28.5/69 ≈ 41%. Contra un short stack (35BB) que va all-in en el turn, el rango es MUCHO más amplio que el de un stack profundo: en NL25 los short stacks shovean turn con cualquier pareja, top pair, segundas parejas, draws e incluso aire al sentirse 'comprometidos' tras pagar el flop. Contra ese rango amplio tu equidad real sube a ~45-48%, superando el 41% requerido. Paga — los short stacks son explotables porque su umbral de shove es mucho más bajo.",
   en:"CALL. J♥T♥ on 9♥8♠2♥4♣: you have a heart flush draw (9 outs) + OESD (J-T-9-8, completes with Q or 7) — accounting for overlap (Q♥ and 7♥ already count as flush outs), the total is ≈ 15 clean outs = ~32-35% raw equity on its own. ER = 28.5/69 ≈ 41%. Against a short stack (35BB) shoving the turn, the range is MUCH wider than a deep stack's: in NL25, short stacks shove turns with any pair, top pair, second pairs, draws, and even air once they feel 'committed' after calling the flop. Against that wide range your real equity rises to ~45-48%, exceeding the required 41%. Call — short stacks are exploitable because their shoving threshold is much lower."},

  // S1907: Overbet gigante de un nit que casi nunca overbet → FOLD (lectura de frecuencia)
  {id:1907,type:"facing",hand:"T♠ T♣",board:"8♣4♦K♥5♣",street:"river",open:false,
   ctx:"facing_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg muy nítico (VPIP 16%, PFR 13%, Overbet River freq 2%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 8♣4♦2♠: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn K♥: BB checkea. Hero checkea. Bote: 12.5BB.\nRiver 5♣: BB apuesta 25BB (overbet ≈200% del bote).",
   descEn:"NL25 · BTN vs BB · Very nitty reg (VPIP 16%, PFR 13%, Overbet River freq 2%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 8♣4♦2♠: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn K♥: BB checks. Hero checks. Pot: 12.5BB.\nRiver 5♣: BB bets 25BB (overbet ≈200% of pot).",
   es:"FOLD. TT (overpair) en 8-4-2-K-5 no supera ni al K ni a las combinaciones de dos pares posibles. ER = 25/(25+37.5) = 40%. La clave aquí no es la equidad — es el PERFIL: este reg es extremadamente nítico (VPIP 16%) y solo overbet el río el 2% de las veces. Cuando un jugador así, que prácticamente NUNCA usa este movimiento, decide hacerlo justo en esta mano (tras checkear el turn de forma pasiva), la lectura es inequívoca: representa valor nuts casi siempre (KK, K8, K5, 88, 55, 84 dos pares, 22 set). Cuanto más rara es una acción para un jugador concreto, más fuerte es la señal cuando ocurre. Aunque ER=40% parezca alcanzable, tu equidad real vs este rango específico es casi 0%. Foldea — esto es perfil de jugador, no matemáticas de bote.",
   en:"FOLD. TT (overpair) on 8-4-2-K-5 beats neither the K nor the possible two-pair combos. ER = 25/(25+37.5) = 40%. The key here isn't equity — it's the PROFILE: this reg is extremely nitty (VPIP 16%) and only overbets the river 2% of the time. When a player who almost NEVER makes this move decides to do it on this exact hand (after passively checking the turn), the read is unmistakable: it represents nut value almost always (KK, K8, K5, 88, 55, 84 two pair, 22 set). The rarer an action is for a specific player, the stronger the signal when it happens. Even though ER=40% looks reachable, your real equity vs this specific range is near 0%. Fold — this is player profiling, not pot math."},

  // S1908: Set de fondo demotado por river de 4 a un palo, triple barril LAG → FOLD
  {id:1908,type:"facing",hand:"4♠ 4♣",board:"K♦9♦4♥7♦5♦",street:"river",open:false,
   ctx:"facing_river",pos:"BB",callPos:"CO",
   descEs:"NL25 · BB vs CO · LAG (VPIP 38%, PFR 30%, CBet River 60%)\nPreflop: CO abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop K♦9♦4♥: Hero checkea (set de 4s). CO apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 7♦ (segundo diamante): Hero checkea. CO apuesta 9BB. Hero paga. Bote: 30.5BB.\nRiver 5♦ (CUARTO diamante): Hero checkea. CO apuesta 30.5BB (pot).",
   descEn:"NL25 · BB vs CO · LAG (VPIP 38%, PFR 30%, CBet River 60%)\nPreflop: CO opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop K♦9♦4♥: Hero checks (set of 4s). CO bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 7♦ (second diamond): Hero checks. CO bets 9BB. Hero calls. Pot: 30.5BB.\nRiver 5♦ (FOURTH diamond): Hero checks. CO bets 30.5BB (pot-size).",
   es:"FOLD. 44 (set de cuatros) en K♦9♦4♥7♦5♦ — el river trae el CUARTO diamante. Tu trío de 4s ya no es una mano fuerte: cualquier diamante en la mano de CO (necesita solo UNO) le da color, y además cualquier K, 9, 7 o 5 le da dos pares o un full house, todos superando tu trío. ER = 30.5/61 = 50%, pero tu equidad real vs el rango de barril triple de un LAG en un river que se volvió monocromático es ~20-25%. Un jugador agresivo que dispara la tercera calle justo cuando el tablero se vuelve de 4 a un palo casi siempre tiene precisamente eso: un color, o un full house. Tu set, que era una mano monstruo en el flop, se convirtió en bluff catcher por el river. Foldea — reevalúa la fuerza de tu mano en cada calle según cómo cambia el tablero.",
   en:"FOLD. 44 (set of fours) on K♦9♦4♥7♦5♦ — the river brings the FOURTH diamond. Your trip 4s are no longer a strong hand: any diamond in CO's hand (just ONE needed) gives them a flush, and any K, 9, 7, or 5 gives them two pair or a full house, all beating your trips. ER = 30.5/61 = 50%, but your real equity vs a LAG's triple-barrel range on a river that turned monochromatic is ~20-25%. An aggressive player firing the third street exactly when the board turns 4-to-a-suit almost always has precisely that: a flush, or a full house. Your set, a monster hand on the flop, became a bluff catcher by the river. Fold — reassess your hand's strength on every street as the board changes."},

  // S1909: Donk lead tras doble check-back, rango "capado" → CALL
  {id:1909,type:"facing",hand:"K♣ 9♣",board:"Q♠9♥4♦2♠J♥",street:"river",open:true,
   ctx:"facing_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Reg (VPIP 26%, PFR 20%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♠9♥4♦: BB checkea. Hero checkea (segunda pareja, control de bote). Bote: 5.5BB.\nTurn 2♠: BB checkea. Hero checkea de nuevo. Bote: 5.5BB.\nRiver J♥: BB sale apostando (donk bet) 5BB (≈91% del bote) — primera apuesta de BB en la mano.",
   descEn:"NL25 · CO vs BB · Reg (VPIP 26%, PFR 20%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♠9♥4♦: BB checks. Hero checks (second pair, pot control). Pot: 5.5BB.\nTurn 2♠: BB checks. Hero checks again. Pot: 5.5BB.\nRiver J♥: BB leads (donk bet) 5BB (≈91% of pot) — BB's first bet of the hand.",
   es:"PAGAR. K9 (pareja de 9s, segunda pareja) en Q-9-4-2-J. ER = 5/(5+10.5) ≈ 32%. Hero checkeó DOS calles seguidas (flop y turn), así que BB nunca tuvo presión y su rango para 'valor genuino acumulado' está limitado — no tenía nada con qué apostar antes. Ahora, en el river, BB sale apostando por primera vez en toda la mano (donk bet). Este patrón — check-check y luego donk river — en la población de NL25 representa un rango polarizado pero con un componente de farol significativo: o BB conectó algo en el river (una J, un 9 mejorado) o intenta robar el bote al ver que nadie mostró interés. K9 le gana a los faroles puros y a algunas manos marginales que también podrían apostar aquí. ER 32% es alcanzable. Paga.",
   en:"CALL. K9 (pair of 9s, second pair) on Q-9-4-2-J. ER = 5/(5+10.5) ≈ 32%. Hero checked TWO streets in a row (flop and turn), so BB was never under pressure and their range for 'genuine accumulated value' is limited — they had nothing to bet with earlier. Now, on the river, BB leads for the first time in the entire hand (donk bet). This pattern — check-check then donk river — in NL25 population represents a polarized range but with a significant bluff component: either BB connected on the river (a J, an improved 9) or is trying to steal the pot seeing neither player showed interest. K9 beats pure bluffs and some marginal hands that could also bet here. ER 32% is reachable. Call."},

  // S1910: Color bajo en tablero de 4 a un palo, overbet de río → FOLD
  {id:1910,type:"facing",hand:"6♠ 3♥",board:"J♠8♠5♠2♠7♥",street:"river",open:false,
   ctx:"facing_river",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Reg (VPIP 27%, PFR 21%, CBet River 47%)\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop J♠8♠5♠ (proyecto de color): Hero checkea. BTN apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 2♠ (CUARTA pica — color hecho): Hero checkea. BTN apuesta 9BB. Hero paga. Bote: 30.5BB.\nRiver 7♥: Hero checkea. BTN apuesta 28BB (overbet ≈92% del bote).",
   descEn:"NL25 · BB vs BTN · Reg (VPIP 27%, PFR 21%, CBet River 47%)\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop J♠8♠5♠ (flush draw): Hero checks. BTN bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 2♠ (FOURTH spade — flush made): Hero checks. BTN bets 9BB. Hero calls. Pot: 30.5BB.\nRiver 7♥: Hero checks. BTN bets 28BB (overbet ≈92% of pot).",
   es:"FOLD. 6♠3♥ te da un color (J-8-6-5-2 de picas) en un tablero con 4 picas (J♠8♠5♠2♠). ER = 28/(28+58.5) ≈ 32%. PERO en un tablero de 4 a un palo, todos los colores comparten las mismas 4 cartas — la única diferencia es la quinta carta de cada jugador. Tu 6♠ es muy baja: cualquier rival con 9♠, T♠, Q♠, K♠ o A♠ (5 rangos completos de combos) tiene un color superior al tuyo. Un BTN reg que paga dos calles con sizing creciente y luego OVERBET el río en un tablero de 4 picas tiene un rango cargado de esos colores superiores — pocos jugadores pagan dos calles sin al menos un color decente o un proyecto alto. Tu color de 6 es uno de los peores posibles aquí. ER 32% no compensa cuando tu 'mano hecha' pierde contra buena parte del rango de overbet. Foldea — los colores bajos en tableros de 4 a un palo son trampas clásicas de equidad invertida.",
   en:"FOLD. 6♠3♥ gives you a flush (J-8-6-5-2 of spades) on a board with 4 spades (J♠8♠5♠2♠). ER = 28/(28+58.5) ≈ 32%. BUT on a 4-to-a-suit board, every flush shares the same 4 board cards — the only difference is each player's fifth card. Your 6♠ is very low: any villain with 9♠, T♠, Q♠, K♠, or A♠ (5 full ranks of combos) has a better flush than yours. A BTN reg who calls two streets with increasing sizing and then OVERBETS the river on a 4-spade board has a range loaded with those better flushes — few players call two streets without at least a decent flush or a high flush draw. Your 6-flush is one of the worst possible here. ER 32% doesn't compensate when your 'made hand' loses to a large chunk of the overbet range. Fold — low flushes on 4-to-a-suit boards are classic reverse-equity traps."},

  // S1911: Donk overbet de un fish pasivo tras 2 calles calladas → FOLD
  {id:1911,type:"facing",hand:"A♠ Q♦",board:"Q♣7♦2♠9♠4♣",street:"river",open:false,
   ctx:"facing_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Fish pasivo (VPIP 55%, PFR 6%, Donk Lead River <3%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♣7♦2♠: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn 9♠: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 4♣: BB sale apostando (donk lead) 40BB (overbet ≈140% del bote).",
   descEn:"NL25 · CO vs BB · Passive fish (VPIP 55%, PFR 6%, Donk Lead River <3%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♣7♦2♠: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn 9♠: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 4♣: BB leads (donk bet) 40BB (overbet ≈140% of pot).",
   es:"FOLD. AQ (top pair top kicker) en Q-7-2-9-4. ER = 40/(40+68.5) ≈ 37%, parece alcanzable. Pero BB es un fish pasivo que casi NUNCA lidera el river (donk lead <3%) y que ha pagado dos calles sin mostrar ninguna iniciativa. Cuando un jugador así, de repente, sale apostando un OVERBET de 140% del bote sin que nadie le haya dado pie — esto no es un farol. Los fishes pasivos no improvisan faroles gigantes; cuando rompen su patrón pasivo con una apuesta enorme no solicitada, casi siempre es porque conectaron algo monstruoso (un set, dos pares, un Q rivereado con kicker mejor, o incluso trip 9s/4s). Tu AQ, una mano fuerte en el flop, ahora es un bluff catcher contra un rango que apenas tiene faroles. Foldea — la acción NO SOLICITADA y fuera de patrón es la señal más fuerte.",
   en:"FOLD. AQ (top pair top kicker) on Q-7-2-9-4. ER = 40/(40+68.5) ≈ 37%, looks reachable. But BB is a passive fish who almost NEVER leads the river (donk lead <3%) and has called two streets showing zero initiative. When a player like that suddenly leads with a 140% pot OVERBET unprompted — this is not a bluff. Passive fish don't improvise giant bluffs; when they break their passive pattern with a huge unsolicited bet, it's almost always because they connected with something monstrous (a set, two pair, a rivered Q with a better kicker, or even trip 9s/4s). Your AQ, a strong hand on the flop, is now a bluff catcher against a range with almost no bluffs. Fold — unsolicited, out-of-pattern action is the strongest signal."},

  // S1912: Dos pares "de fondo" (segundo mejor) vs all-in river en board con K → FOLD
  {id:1912,type:"facing",hand:"T♠ 9♠",board:"K♦9♦T♣3♣6♥",street:"river",open:false,
   ctx:"facing_allin",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg (VPIP 25%, PFR 19%) · All-in en el river\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop K♦9♦T♣: BB checkea. Hero apuesta 3.5BB (dos pares). BB paga. Bote: 12.5BB.\nTurn 3♣: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 6♥: BB va all-in por 45BB. Bote total si pagas: 118.5BB. Coste del call: 45BB.",
   descEn:"NL25 · BTN vs BB · Reg (VPIP 25%, PFR 19%) · All-in on river\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop K♦9♦T♣: BB checks. Hero bets 3.5BB (two pair). BB calls. Pot: 12.5BB.\nTurn 3♣: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 6♥: BB goes all-in for 45BB. Total pot if you call: 118.5BB. Cost of call: 45BB.",
   es:"FOLD. T9 te da dos pares (dieces y nueves) en K-9-T-3-6 — pero es el SEGUNDO mejor dos pares posible en este tablero. Cualquier Kx (KT, K9, o KK) hace un dos pares superior (Reyes con dieces/nueves), y cualquier 9 o T extra en la mano del rival hace un trío que también te supera. ER = 45/(45+118.5) ≈ 28%. Un jugador que paga dos calles en un tablero con un Rey en la cima y luego va all-in en el río casi siempre tiene precisamente ese Rey emparejado — su rango de call-call-shove está cargado de Kx. ER bajo no significa call automático: tu equidad real vs un rango lleno de Kx es ~20%. La lección: 'tener dos pares' no es suficiente — siempre compara tu mano contra los DOS PARES SUPERIORES que el board permite. Foldea.",
   en:"FOLD. T9 gives you two pair (tens and nines) on K-9-T-3-6 — but it's the SECOND-best two pair possible on this board. Any Kx (KT, K9, or KK) makes a higher two pair (Kings with tens/nines), and any extra 9 or T in villain's hand makes trips that also beat you. ER = 45/(45+118.5) ≈ 28%. A player who calls two streets on a board topped by a King and then shoves the river almost always has that King paired — their call-call-shove range is loaded with Kx. A low ER doesn't mean an automatic call: your real equity vs a Kx-heavy range is ~20%. The lesson: 'having two pair' isn't enough — always compare your hand against the BEST two pair the board allows. Fold."},

  // S1913: Bluff-catch ace-high vs all-in de un maníaco (lectura de perfil) → CALL
  {id:1913,type:"facing",hand:"A♣ J♣",board:"8♠5♦2♥K♦Q♣",street:"river",open:true,
   ctx:"facing_allin",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Maníaco (VPIP 62%, PFR 45%, Bet River freq 78%) · All-in en el río\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop 8♠5♦2♥: Hero checkea. BTN apuesta 4BB. Hero paga. Bote: 13.5BB.\nTurn K♦: Hero checkea. BTN apuesta 11BB. Hero paga. Bote: 35.5BB.\nRiver Q♣: Hero checkea. BTN va all-in por 35BB. Bote total si pagas: 105.5BB. Coste del call: 35BB.",
   descEn:"NL25 · BB vs BTN · Maniac (VPIP 62%, PFR 45%, Bet River freq 78%) · All-in on river\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop 8♠5♦2♥: Hero checks. BTN bets 4BB. Hero calls. Pot: 13.5BB.\nTurn K♦: Hero checks. BTN bets 11BB. Hero calls. Pot: 35.5BB.\nRiver Q♣: Hero checks. BTN goes all-in for 35BB. Total pot if you call: 105.5BB. Cost of call: 35BB.",
   es:"PAGAR. AJ no tiene ni pareja en 8-5-2-K-Q. ER = 35/(35+105.5) ≈ 25%. Contra un jugador normal, esto sería un fold trivial. Pero BTN es un MANÍACO (VPIP 62%, apuesta el río el 78% de las veces — la frecuencia más alta posible). Contra este perfil, 'ir all-in en el río' no es una señal de fuerza: es simplemente lo que hace SIEMPRE, tenga lo que tenga. Su rango de shove incluye una proporción enorme de manos sin showdown (proyectos fallidos, pares bajos, incluso aire puro). AJ ace-high le gana a todos los faroles puros y a varias manos de pareja baja con kicker peor. ER=25% es alcanzable contra este rango tan amplio. La lección: el ER no es un número fijo — depende COMPLETAMENTE del rango del rival, y el rango de un maníaco en el río es radicalmente distinto al de un jugador normal. Paga.",
   en:"CALL. AJ has no pair on 8-5-2-K-Q. ER = 35/(35+105.5) ≈ 25%. Against a normal player, this would be a trivial fold. But BTN is a MANIAC (VPIP 62%, bets the river 78% of the time — the highest frequency possible). Against this profile, 'shoving the river' is not a sign of strength: it's simply what they ALWAYS do, regardless of their hand. Their shoving range includes a huge proportion of no-showdown hands (missed draws, low pairs, even pure air). Ace-high AJ beats all pure bluffs and several low-pair hands with a worse kicker. ER=25% is reachable against such a wide range. The lesson: ER isn't a fixed number — it depends ENTIRELY on villain's range, and a maniac's river range is radically different from a normal player's. Call."},

  // S1914: Escalera hecha en board de 3 colores, all-in river → CALL
  {id:1914,type:"facing",hand:"7♠ 6♠",board:"9♦8♣5♥T♦2♦",street:"river",open:true,
   ctx:"facing_allin",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg (VPIP 27%, PFR 21%) · All-in en el río\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 9♦8♣5♥ (escalera abierta): BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn T♦ (escalera completa: 6-7-8-9-T): BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 2♦ (tercer diamante): BB va all-in por 50BB. Bote total si pagas: 128.5BB. Coste del call: 50BB.",
   descEn:"NL25 · BTN vs BB · Reg (VPIP 27%, PFR 21%) · All-in on river\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 9♦8♣5♥ (open-ended draw): BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn T♦ (straight complete: 6-7-8-9-T): BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 2♦ (third diamond): BB goes all-in for 50BB. Total pot if you call: 128.5BB. Cost of call: 50BB.",
   es:"PAGAR. 76 hace una escalera (6-7-8-9-T) en 9-8-5-T-2, en un tablero con 3 diamantes en el river. ER = 50/(50+128.5) ≈ 39%. Tu escalera pierde SOLO contra: (1) cualquier mano con dos diamantes (color), o (2) cualquier J (que haría una escalera más alta, J-T-9-8-7). Fuera de esas combinaciones específicas, tu escalera le gana a TODO — sets, dos pares, pares altos, proyectos que no llegaron. El número de combos de color + J es relativamente pequeño comparado con el resto del rango de shove de BB en NL25 (que también incluye sets 'comprometidos' tras pagar dos calles, dos pares, etc.). Tu equidad real ronda el 55-60%, muy por encima del 39% requerido. Paga — una escalera hecha rara vez es un fold, incluso con un color posible en mesa.",
   en:"CALL. 76 makes a straight (6-7-8-9-T) on 9-8-5-T-2, on a board with 3 diamonds by the river. ER = 50/(50+128.5) ≈ 39%. Your straight loses ONLY to: (1) any hand with two diamonds (flush), or (2) any J (which would make a higher straight, J-T-9-8-7). Outside those specific combos, your straight beats EVERYTHING — sets, two pair, high pairs, busted draws. The number of flush + J combos is relatively small compared to the rest of BB's shoving range in NL25 (which also includes 'committed' sets after calling two streets, two pair, etc.). Your real equity is around 55-60%, well above the required 39%. Call — a made straight is rarely a fold, even with a flush possible on board."},

  // S1915: La rueda (escalera más baja) es casi siempre la mejor mano → CALL
  {id:1915,type:"facing",hand:"A♦ 2♣",board:"5♥4♠3♦9♣K♠",street:"river",open:true,
   ctx:"facing_allin",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Reg (VPIP 26%, PFR 20%) · All-in en el río\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop 5♥4♠3♦ (Hero hace la rueda: A-2-3-4-5): Hero checkea. BTN apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 9♣: Hero checkea. BTN apuesta 8BB. Hero paga. Bote: 28.5BB.\nRiver K♠: Hero checkea. BTN va all-in por 60BB. Bote total si pagas: 148.5BB. Coste del call: 60BB.",
   descEn:"NL25 · BB vs BTN · Reg (VPIP 26%, PFR 20%) · All-in on river\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop 5♥4♠3♦ (Hero makes the wheel: A-2-3-4-5): Hero checks. BTN bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 9♣: Hero checks. BTN bets 8BB. Hero calls. Pot: 28.5BB.\nRiver K♠: Hero checks. BTN goes all-in for 60BB. Total pot if you call: 148.5BB. Cost of call: 60BB.",
   es:"PAGAR. A2 hace la escalera más baja (la 'rueda': A-2-3-4-5) en 5-4-3-9-K — un tablero sin color posible y sin parejas. Tu escalera pierde ÚNICAMENTE contra 6-2 (escalera de 6 alta, 6-5-4-3-2), una combinación extremadamente específica y rara (y tú mismo bloqueas un 2). Contra prácticamente cualquier otro shove de río en este board (sets, dos pares, K9 con dos pares, faroles que no llegaron a nada), tu rueda es la mejor mano. ER = 60/(60+148.5) ≈ 29%, pero tu equidad real es ~90%+. La lección avanzada: no dejes que el nombre 'rueda' (la escalera MÁS BAJA) te haga dudar — en términos de fuerza relativa contra el rango del rival, casi siempre es un monstruo. Paga sin dudar.",
   en:"CALL. A2 makes the lowest possible straight (the 'wheel': A-2-3-4-5) on 5-4-3-9-K — a board with no flush possible and no pairs. Your straight loses ONLY to 6-2 (a 6-high straight, 6-5-4-3-2), an extremely specific and rare combo (and you yourself block one of the 2s). Against virtually any other river shove on this board (sets, two pair, K9 two pair, busted bluffs), your wheel is the best hand. ER = 60/(60+148.5) ≈ 29%, but your real equity is ~90%+. The advanced lesson: don't let the name 'wheel' (the LOWEST straight) make you hesitate — in terms of relative strength vs villain's range, it's almost always a monster. Call without hesitation."},

  // S1916: Proyecto combinado (color + escalera) all-in en el flop → CALL
  {id:1916,type:"facing",hand:"K♥ Q♥",board:"J♥T♥3♣",street:"flop",open:true,
   ctx:"facing_allin",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · All-in en el flop\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop J♥T♥3♣ (dos a corazones): BB checkea. Hero apuesta 3.5BB. BB sube all-in a 35BB.\nBote total si pagas: 75.5BB. Coste del call: 31.5BB adicionales.",
   descEn:"NL25 · CO vs BB · All-in on flop\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop J♥T♥3♣ (two hearts): BB checks. Hero bets 3.5BB. BB raises all-in to 35BB.\nTotal pot if you call: 75.5BB. Cost of call: 31.5BB more.",
   es:"PAGAR. K♥Q♥ en J♥T♥3♣: tienes proyecto de color (4 corazones, 9 outs) + escalera abierta (K-Q necesita A o 9, 8 outs) — descontando solapamientos (A♥ y 9♥ ya cuentan como outs de color), el total es ≈ 15 outs limpios. Al ser all-in en el FLOP, ves DOS cartas (turn y río), así que tu equidad real con ~15 outs es ~54% (regla del 4 aplicada a dos calles, ajustada por solapamiento). ER = 31.5/(31.5+75.5) ≈ 29%. Con ~54% de equidad vs un ER de 29%, este es un call claro y rentable — un proyecto combinado (color + escalera) all-in en el flop casi siempre es +EV incluso contra un rango fuerte de check-raise (sets, dos pares), porque tienes dos cartas para mejorar y una cantidad enorme de outs limpios.",
   en:"CALL. K♥Q♥ on J♥T♥3♣: you have a flush draw (4 hearts, 9 outs) + an open-ended straight draw (K-Q needs an A or 9, 8 outs) — accounting for overlap (A♥ and 9♥ already count as flush outs), the total is ≈ 15 clean outs. Being all-in on the FLOP, you see TWO cards (turn and river), so your real equity with ~15 outs is ~54% (rule of 4 applied across two streets, adjusted for overlap). ER = 31.5/(31.5+75.5) ≈ 29%. With ~54% equity vs a 29% ER, this is a clear, profitable call — a combo draw (flush + straight) all-in on the flop is almost always +EV even against a strong check-raise range (sets, two pair), because you have two cards to improve and a huge number of clean outs."},

  // S1917: Float fallido, river de un jugador que "nunca farolea" → FOLD
  {id:1917,type:"facing",hand:"K♣ J♦",board:"9♠6♦2♣4♥Q♠",street:"river",open:false,
   ctx:"facing_river",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Reg pasivo (VPIP 22%, PFR 17%, Bet River freq 8%)\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop 9♠6♦2♣: BTN apuesta 3.5BB. Hero paga (float). Bote: 12.5BB.\nTurn 4♥: BTN checkea. Hero checkea (sin buena carta para farolear). Bote: 12.5BB.\nRiver Q♠: BTN apuesta 5BB (≈40% del bote).",
   descEn:"NL25 · BB vs BTN · Passive reg (VPIP 22%, PFR 17%, Bet River freq 8%)\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop 9♠6♦2♣: BTN bets 3.5BB. Hero calls (float). Pot: 12.5BB.\nTurn 4♥: BTN checks. Hero checks (no good bluff card). Pot: 12.5BB.\nRiver Q♠: BTN bets 5BB (≈40% of pot).",
   es:"FOLD. KJ no conecta nada en 9-6-2-4-Q — ni siquiera una pareja (carta alta). ER = 5/(5+17.5) ≈ 22%. BTN es un jugador pasivo que apuesta el río con muy poca frecuencia (8%) — casi nunca con farol. Cuando un jugador así apuesta, incluso con un tamaño pequeño (40% del bote), representa valor genuino con muy alta probabilidad (un Q, una sobrepareja, dos pares). KJ no le gana a casi nada de su rango de apuesta — ni siquiera tienes un bluff catcher real, solo carta alta. El ER de 22% no importa cuando tu equidad real es prácticamente cero contra un rango ~95% valor. Foldea — el float que no se completó con una buena carta de farol simplemente se convierte en 'rendirse' al river.",
   en:"FOLD. KJ connects with nothing on 9-6-2-4-Q — not even a pair (king-high). ER = 5/(5+17.5) ≈ 22%. BTN is a passive player who bets the river very rarely (8%) — almost never as a bluff. When a player like this bets, even with a small size (40% of pot), it represents genuine value with very high probability (a Q, an overpair, two pair). KJ beats almost nothing in their betting range — you don't even have a real bluff catcher, just king-high. The 22% ER doesn't matter when your real equity is near zero against a ~95% value range. Fold — a float that didn't complete with a good bluffing card simply becomes 'give up' on the river."},

  // S1918: Overpair vs all-in cuando el river completa color Y empareja la cima → FOLD
  {id:1918,type:"facing",hand:"J♠ J♦",board:"7♥4♥2♣9♥K♥",street:"river",open:false,
   ctx:"facing_allin",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Reg tight (VPIP 19%, PFR 15%, Shove River freq 4%) · All-in en el río\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 7♥4♥2♣: BB checkea. Hero apuesta 3.5BB (JJ, sobrepareja). BB paga. Bote: 12.5BB.\nTurn 9♥ (segundo corazón): BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver K♥ (tercer corazón + Rey): BB va all-in por 50BB. Bote total si pagas: 128.5BB. Coste del call: 50BB.",
   descEn:"NL25 · BTN vs BB · Tight reg (VPIP 19%, PFR 15%, Shove River freq 4%) · All-in on river\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 7♥4♥2♣: BB checks. Hero bets 3.5BB (JJ, overpair). BB calls. Pot: 12.5BB.\nTurn 9♥ (second heart): BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver K♥ (third heart + a King): BB goes all-in for 50BB. Total pot if you call: 128.5BB. Cost of call: 50BB.",
   es:"FOLD. JJ (overpair) en 7-4-2-9-K — el river trae el TERCER corazón, completando un color para cualquier rival con un solo corazón en mano, Y además el K♥ empareja la cima del tablero, dándole a cualquier Kx una pareja superior a tu JJ. ER = 50/(50+128.5) ≈ 28%. Un reg tight (solo va all-in en el río el 4% de las veces) que de repente apuesta TODO justo cuando caen DOS texturas peligrosas a la vez (color completo + overcard nueva) representa casi exclusivamente colores o KK/K9/K7/K4 etc. Tu JJ, una mano de valor sólida en el flop, ahora pierde contra colores Y contra cualquier Rey. Foldea — los overpairs pierden su brillo cuando el river trae simultáneamente un overcard Y completa un color, y más aún si el villano nunca shovea sin motivo.",
   en:"FOLD. JJ (overpair) on 7-4-2-9-K — the river brings the THIRD heart, completing a flush for any villain with a single heart, AND the K♥ also pairs the top of the board, giving any Kx a higher pair than your JJ. ER = 50/(50+128.5) ≈ 28%. A tight reg (shoves the river only 4% of the time) who suddenly shoves EVERYTHING right when TWO dangerous textures land at once (a completed flush + a new overcard) represents almost exclusively flushes or KK/K9/K7/K4, etc. Your JJ, a solid value hand on the flop, now loses to flushes AND to any King. Fold — overpairs lose their shine when the river simultaneously brings an overcard AND completes a flush, especially against a villain who never shoves without reason."},

  // S1919: Color casi nuts hecho en el turn (solo pierde contra color de As), all-in → CALL
  {id:1919,type:"facing",hand:"Q♦ J♦",board:"K♦7♦2♦9♣",street:"turn",open:true,
   ctx:"facing_allin",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Reg (VPIP 27%, PFR 21%) · All-in en el turn\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop K♦7♦2♦ (Hero hace color K-Q-J-7-2 con QJ): Hero checkea. BTN apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 9♣: Hero checkea. BTN va all-in por 50BB. Bote total si pagas: 128.5BB. Coste del call: 50BB.",
   descEn:"NL25 · BB vs BTN · Reg (VPIP 27%, PFR 21%) · All-in on turn\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop K♦7♦2♦ (Hero makes a flush K-Q-J-7-2 with QJ): Hero checks. BTN bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 9♣: Hero checks. BTN goes all-in for 50BB. Total pot if you call: 128.5BB. Cost of call: 50BB.",
   es:"PAGAR. QJ de diamantes te da un color K-Q-J-7-2 (usando el K♦ del board) en K♦7♦2♦ — un color casi nuts. Solo pierdes contra A♦x (color de As), una combinación muy específica y poco frecuente. ER = 50/(50+128.5) ≈ 28%, y tu equidad real vs el rango de shove (que incluye sets, dos pares, colores más bajos, y solo ocasionalmente A♦x) es ~85%+. Paga — un color que solo pierde contra el color de As es, en la práctica, una mano de all-in casi siempre, sin importar en qué calle llegue el shove.",
   en:"CALL. QJ of diamonds gives you a flush K-Q-J-7-2 (using the K♦ on the board) on K♦7♦2♦ — a near-nut flush. You only lose to A♦x (the Ace-high flush), a very specific and infrequent combo. ER = 50/(50+128.5) ≈ 28%, and your real equity vs the shoving range (which includes sets, two pair, lower flushes, and only occasionally A♦x) is ~85%+. Call — a flush that only loses to the nut flush is, in practice, an all-in hand almost every time, regardless of which street the shove comes on."},

  // S1920: Lectura de tilt — un LAG que viene de perder botes grandes sobre-farolea → CALL
  {id:1920,type:"facing",hand:"K♦ T♦",board:"T♣8♥3♠6♦Q♣",street:"river",open:true,
   ctx:"facing_river",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · LAG (VPIP 40%, PFR 32%, Bet River freq 55%) — acaba de perder dos botes grandes seguidos\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop T♣8♥3♠: Hero checkea (pareja de dieces). BTN apuesta 3.5BB. Hero paga. Bote: 12.5BB.\nTurn 6♦: Hero checkea. BTN apuesta 8BB. Hero paga. Bote: 28.5BB.\nRiver Q♣: Hero checkea. BTN apuesta 30BB (overbet ≈105% del bote).",
   descEn:"NL25 · BB vs BTN · LAG (VPIP 40%, PFR 32%, Bet River freq 55%) — just lost two big pots in a row\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop T♣8♥3♠: Hero checks (pair of tens). BTN bets 3.5BB. Hero calls. Pot: 12.5BB.\nTurn 6♦: Hero checks. BTN bets 8BB. Hero calls. Pot: 28.5BB.\nRiver Q♣: Hero checks. BTN bets 30BB (overbet ≈105% of pot).",
   es:"PAGAR. KT (pareja de dieces, kicker Rey) en T-8-3-6-Q. ER = 30/(30+58.5) ≈ 34%. El factor decisivo aquí no es solo el board ni los blockers, sino el ESTADO EMOCIONAL del rival: este LAG ha perdido dos botes grandes seguidos en los últimos minutos (visible en el historial reciente de la sesión). Jugadores en 'tilt' — especialmente perfiles ya agresivos (VPIP 40%, Bet River 55%) — tienden a sobre-farolear significativamente más que su frecuencia base, intentando 'recuperar' lo perdido mediante agresión. Su rango de triple barril ahora mismo está más cargado de faroles que en una situación neutral. KT le gana a una parte importante de ese rango ampliado de faroles. Paga — los reads de tilt son una capa de información adicional sobre las stats de HUD, y en NL25 son sorprendentemente predictivos.",
   en:"CALL. KT (pair of tens, King kicker) on T-8-3-6-Q. ER = 30/(30+58.5) ≈ 34%. The deciding factor here isn't just the board or blockers, but villain's EMOTIONAL STATE: this LAG just lost two big pots in a row in the last few minutes (visible in the recent session history). Players on 'tilt' — especially already-aggressive profiles (VPIP 40%, Bet River 55%) — tend to over-bluff significantly more than their baseline frequency, trying to 'win back' what they lost through aggression. Their triple-barrel range right now is more bluff-heavy than in a neutral situation. KT beats a meaningful chunk of that expanded bluff range. Call — tilt reads are an extra layer of information on top of standard HUD stats, and in NL25 they're surprisingly predictive."},

];
