// ─── VALUE BET — situaciones nuevas ──────────────────────────────────────────
// Añade aquí nuevas situaciones de tipo "vbet" en lugar de editar el array
// VBET_SITUATIONS gigante dentro de grinders-manual.jsx.
// Mismo formato: { id, type:"vbet", hand, board, street, open, size, ctx, pos, callPos,
//                   descEs, descEn, es, en }
// IDs sugeridos: a partir de 1500 (los existentes van 401-4xx).
// bluff:true → Hero decide si disparar un barrel como farol (bet) o ceder (check).
//   open=true → apostar (farol) es correcto; open=false → checkear es correcto.
//   ctx: bluff_turn | bluff_river | bluff_delayed | bluff_raise
export const VBET_SITUATIONS_EXTRA = [

  // ── DOBLE BARREL / TURN BLUFFS (7) ───────────────────────────────────────────
  // Hero apostó el flop y fue pagado; decide si disparar el segundo barrel en el turn

  // 1501: Turn flush draw — disparar el doble barrel ✓
  {id:1501,type:"vbet",hand:"A♠8♠",board:"K♥5♠3♠9♦",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular sólido (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop K♥5♠3♠: BB checkea. Hero apuesta 3.5BB (proyecto de color de picas + overcard As). BB paga. Bote: 12.5BB.\nTurn 9♦: BB checkea. Hero actúa.",
   descEn:"NL25 · BTN vs BB · Solid regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop K♥5♠3♠: BB checks. Hero bets 3.5BB (flush draw + overcard Ace). BB calls. Pot: 12.5BB.\nTurn 9♦: BB checks. Hero acts.",
   es:"APOSTAR (FAROL). A8s con proyecto de color de picas (9 outs) en K♥5♠3♠9♦: factores a favor del doble barrel — equidad alta (≈36% contra un rango de pago razonable), posición IP, carta de turn neutra que no mejora los rangos de pago del BB más que el tuyo, y el regular tiene MDF que cumplir (foldea ~50% con la bet). Dispara el segundo barrel.",
   en:"BET (BLUFF). A8s with a spade flush draw (9 outs) on K♥5♠3♠9♦: factors supporting the double barrel — high equity (≈36% vs a reasonable calling range), IP position, neutral turn card that doesn't improve BB's calling ranges more than yours, and the regular has MDF to meet (folds ≈50% to a bet). Fire the second barrel."},

  // 1502: Turn overcards + gutshot — disparar ✓
  {id:1502,type:"vbet",hand:"Q♦J♦",board:"T♠6♣2♥8♠",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 22%, PFR 16%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop T♠6♣2♥: BB checkea. Hero apuesta 3.5BB (two overcards + backdoor straight). BB paga. Bote: 12.5BB.\nTurn 8♠: BB checkea. Hero actúa con QJ (gutshot a 9, dos overcards).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 22%, PFR 16%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop T♠6♣2♥: BB checks. Hero bets 3.5BB (two overcards + backdoor straight). BB calls. Pot: 12.5BB.\nTurn 8♠: BB checks. Hero acts with QJ (gutshot to 9, two overcards).",
   es:"APOSTAR (FAROL). QJ tiene gutshot al 9 + dos overcards (Q, J) = ≈10 outs en el turn. La carta 8♠ trae un flush draw adicional al tablero (picas) que puede hacer que el BB foldee draws de picas peores. Tienes posición, equity buena y el BB tiene que defender vs tu bet con una frecuencia que no puede alcanzar con manos mediocres. Dispara.",
   en:"BET (BLUFF). QJ has a gutshot to 9 + two overcards (Q, J) = ≈10 outs on the turn. The 8♠ card brings an additional flush draw (spades) that may make BB fold worse spade draws. You have position, good equity, and BB can't defend vs your bet with enough frequencies using mediocre hands. Fire."},

  // 1503: Turn sin equity, tablero cambiado — checkear ✓
  {id:1503,type:"vbet",hand:"7♦6♦",board:"A♠K♣9♥J♦",street:"turn",open:false,size:null,bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop A♠K♣9♥: BB checkea. Hero apuesta 3.5BB (dos overcards ampliadas, no conecta en absoluto). BB paga. Bote: 12.5BB.\nTurn J♦: BB checkea. Hero actúa con 76o (sin equity en este tablero).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop A♠K♣9♥: BB checks. Hero bets 3.5BB (extended two overcards, doesn't connect). BB calls. Pot: 12.5BB.\nTurn J♦: BB checks. Hero acts with 76o (no equity on this board).",
   es:"CHECKEAR. 76o en A-K-9-J: sin equity real (no conecta con ninguna carta del board), sin draw, sin posibilidad de mejorar. El tablero A-K-J-9 es extremadamente favorable para el rango del BB (que tiene AX, KX, JX). Disparar un segundo barrel sin equity y sin fold equity suficiente (el BB llamó el flop con una mano que conecta bien) es un error. Checkea y da free card.",
   en:"CHECK. 76o on A-K-9-J: no real equity (doesn't connect with any board card), no draw, no improvement possibility. The A-K-J-9 board is extremely favorable for BB's range (which has AX, KX, JX). Firing a second barrel without equity and without sufficient fold equity (BB called the flop with a well-connected hand) is a mistake. Check and give a free card."},

  // 1504: Turn overcard + backdoor flush, tablero seco — disparar ✓
  {id:1504,type:"vbet",hand:"A♥Q♥",board:"J♣7♦3♠K♥",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Fish calling station (VPIP 55%, WTSD 42%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop J♣7♦3♠: BB checkea. Hero apuesta 3.5BB (dos overcards). BB paga. Bote: 12.5BB.\nTurn K♥: BB checkea. Hero actúa (AQ ahora tiene gutshot al T + backdoor flush).",
   descEn:"NL25 · BTN vs BB · Calling station fish (VPIP 55%, WTSD 42%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop J♣7♦3♠: BB checks. Hero bets 3.5BB (two overcards). BB calls. Pot: 12.5BB.\nTurn K♥: BB checks. Hero acts (AQ now has gutshot to T + backdoor flush).",
   es:"CHECKEAR. Aunque AQ tiene algo de equity (gutshot + backdoor), el factor clave es que el BB es una calling station (WTSD 42%) — contra un fish que llama casi todo, los faroles sin equity sólida tienen EV negativo. El fish no foldea con la frecuencia necesaria para hacer rentable el barrel. La better bluff equity no compensa la baja fold equity. Checkea.",
   en:"CHECK. Although AQ has some equity (gutshot + backdoor), the key factor is that BB is a calling station (WTSD 42%) — against a fish who calls almost everything, bluffs without solid equity have negative EV. The fish doesn't fold with the frequency needed to make the barrel profitable. Better bluff equity doesn't compensate for low fold equity. Check."},

  // 1505: Turn equity + over-representación del rango — disparar ✓
  {id:1505,type:"vbet",hand:"K♣Q♣",board:"J♦9♥2♣T♣",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_turn",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Regular balanceado (VPIP 26%, PFR 20%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop J♦9♥2♣: BB checkea. Hero apuesta 3.5BB. BB paga. Bote: 12.5BB.\nTurn T♣: BB checkea. Hero actúa (KQ tiene straight + flush draw de trébol combinado).",
   descEn:"NL25 · CO vs BB · Balanced regular (VPIP 26%, PFR 20%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop J♦9♥2♣: BB checks. Hero bets 3.5BB. BB calls. Pot: 12.5BB.\nTurn T♣: BB checks. Hero acts (KQ has straight + combined club flush draw).",
   es:"APOSTAR (FAROL). KQ tiene straight draw al As o 8 (8 outs) + flush draw de trébol (9 outs), con solapamientos = ≈15 outs. Equity real ≈35-40%. Además, la carta T♣ sobre-representa el rango del CO (que tiene muchos straight draws, QK, KJ) frente al del BB. Con equidad alta, posición y un rango de continuación sólido, disparar el segundo barrel es claramente +EV.",
   en:"BET (BLUFF). KQ has a straight draw to Ace or 8 (8 outs) + club flush draw (9 outs), with overlaps = ≈15 outs. Real equity ≈35-40%. Additionally, the T♣ card over-represents CO's range (which has lots of straight draws, KQ, KJ) vs BB's. With high equity, position, and a strong continuation range, firing the second barrel is clearly +EV."},

  // 1506: Turn con showdown value — checkear ✓
  {id:1506,type:"vbet",hand:"A♠J♦",board:"Q♦8♣4♥6♠",street:"turn",open:false,size:null,bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♦8♣4♥: BB checkea. Hero apuesta 3.5BB (As overcard + back door flush). BB paga. Bote: 12.5BB.\nTurn 6♠: BB checkea. Hero actúa (AJ tiene As overcard, pero el tablero Q-8-6-4 tiene muchos outs del rango del BB).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♦8♣4♥: BB checks. Hero bets 3.5BB (Ace overcard + backdoor flush). BB calls. Pot: 12.5BB.\nTurn 6♠: BB checks. Hero acts (AJ has Ace overcard, but Q-8-6-4 board has many outs from BB's range).",
   es:"CHECKEAR. AJ tiene showdown value como As alto en este tablero bajo — si el BB tiene un draw fallido, ganas al showdown sin apostar. En cambio, si disparas el barrel, el BB con Q, 8x o 6x no foldea, y mejoras a nada real. Con showdown value y fold equity limitada (el BB llamó el flop con una mano que conecta), checkear protege tu equity mejor que disparar. Checkea.",
   en:"CHECK. AJ has showdown value as Ace-high on this low board — if BB has a missed draw, you win at showdown without betting. However, if you fire the barrel, BB with Q, 8x, or 6x won't fold, and you improve to nothing real. With showdown value and limited fold equity (BB called the flop with a connected hand), checking protects your equity better than firing. Check."},

  // 1507: Turn farol con representación de straight — disparar ✓
  {id:1507,type:"vbet",hand:"5♠4♠",board:"6♣7♦K♥8♠",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_turn",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular sólido (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 6♣7♦K♥: BB checkea. Hero apuesta 3.5BB (open-ended straight draw + dos undercards). BB paga. Bote: 12.5BB.\nTurn 8♠: BB checkea. Hero actúa con 54s (ahora tiene straight al 9 con 5-6-7-8, necesita 9, y el 4 también da straight con 4-5-6-7-8).",
   descEn:"NL25 · BTN vs BB · Solid regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 6♣7♦K♥: BB checks. Hero bets 3.5BB (open-ended straight draw + two undercards). BB calls. Pot: 12.5BB.\nTurn 8♠: BB checks. Hero acts with 54s (now has straight draw to 9 with 5-6-7-8, needs 9, and 4 also gives straight 4-5-6-7-8).",
   es:"APOSTAR (FAROL). 54s tiene 8 outs al straight (cualquier 9 o 3) en 6♣7♦K♥8♠. Además, la carta 8♠ trae dos picas al tablero — 54s también tiene backdoor flush de picas. Equity real ≈20% (8 outs × 2 en river). Pero lo más importante: el tablero 6-7-8 sobre-representa el rango de BTN que abrió (puede tener muchos conectores: 89s, 79s, 56s, 45s). El regular tiene que defender con MDF apropiada pero no puede con manos mediocres. Dispara.",
   en:"BET (BLUFF). 54s has 8 outs to the straight (any 9 or 3) on 6♣7♦K♥8♠. Additionally, the 8♠ brings two spades to the board — 54s also has a backdoor spade flush. Real equity ≈20% (8 outs × 2 on river). More importantly: the 6-7-8 board over-represents BTN's opening range (can have many connectors: 89s, 79s, 56s, 45s). The regular must defend with appropriate MDF but can't with mediocre hands. Fire."},

  // ── TRIPLE BARREL / RIVER BLUFFS (8) ─────────────────────────────────────────
  // Hero apostó flop y turn; decide si disparar el tercer barrel o ceder

  // 1508: River con missed draw y rango bien representado — disparar ✓
  {id:1508,type:"vbet",hand:"A♥Q♥",board:"K♦9♥5♥T♣2♠",street:"river",open:true,size:"large",bluff:true,ctx:"bluff_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop K♦9♥5♥: BB checkea. Hero apuesta 3.5BB (flush draw de corazones + overcard As). BB paga. Bote: 12.5BB.\nTurn T♣: BB checkea. Hero apuesta 8BB (equity sólida, representando KX+). BB paga. Bote: 28.5BB.\nRiver 2♠: BB checkea. Hero actúa (flush draw fallido, As alto).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop K♦9♥5♥: BB checks. Hero bets 3.5BB (heart flush draw + Ace overcard). BB calls. Pot: 12.5BB.\nTurn T♣: BB checks. Hero bets 8BB (solid equity, representing KX+). BB calls. Pot: 28.5BB.\nRiver 2♠: BB checks. Hero acts (missed flush draw, Ace-high).",
   es:"APOSTAR (FAROL). AQ con draw fallido en river: factores a favor del triple barrel — 1) el 2♠ es una carta de river excelente para farolear (no mejora rangos de pago del BB), 2) tu rango tras tres barrels representa fuertemente KX, TX, KT, KK, TT — el BB no puede defender bien con manos mediocres, 3) el 'bluff catcher' del BB (como JX o 9X) tiene solo ≈25% de equity vs tus manos de valor. Dispara el river.",
   en:"BET (BLUFF). AQ with missed draw on river: factors supporting the triple barrel — 1) the 2♠ is an excellent river card for bluffing (doesn't improve BB's calling ranges), 2) your range after three barrels strongly represents KX, TX, KT, KK, TT — BB can't defend well with mediocre hands, 3) BB's 'bluff catcher' (like JX or 9X) has only ≈25% equity vs your value hands. Fire the river."},

  // 1509: River con showdown value — checkear ✓
  {id:1509,type:"vbet",hand:"Q♠J♠",board:"Q♦8♣4♥7♠5♥",street:"river",open:false,size:null,bluff:true,ctx:"bluff_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♦8♣4♥: BB checkea. Hero apuesta 3.5BB (top pair, queen). BB paga. Bote: 12.5BB.\nTurn 7♠: BB checkea. Hero apuesta 8BB (protegiendo top pair). BB paga. Bote: 28.5BB.\nRiver 5♥: BB checkea. Hero actúa (QJ tiene top pair, reina con kicker J).",
   descEn:"NL25 · CO vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♦8♣4♥: BB checks. Hero bets 3.5BB (top pair, queen). BB calls. Pot: 12.5BB.\nTurn 7♠: BB checks. Hero bets 8BB (protecting top pair). BB calls. Pot: 28.5BB.\nRiver 5♥: BB checks. Hero acts (QJ has top pair, queen with J kicker).",
   es:"CHECKEAR. QJ tiene top pair decente con showdown value real — en el river Q♦8♣4♥7♠5♥, una 'bet de valor' podría ser correcta (cobrar a draws fallidos, KX débil). Pero el enfoque es 'value bet vs bluff' con manos que no son clearly-value ni clearly-bluff. QJ medio-value debe checkear el river para proteger su rango de check-call, extraer valor cuando el rival bets, y evitar un raise sorpresa. Checkea.",
   en:"CHECK. QJ has decent top pair with real showdown value — on river Q♦8♣4♥7♠5♥, a value bet could be correct (charging missed draws, weak KX). But the focus is 'value bet vs bluff' with hands that aren't clearly value or clearly bluff. Mid-value QJ should check river to protect its check-call range, extract value when villain bets, and avoid a surprise raise. Check."},

  // 1510: River de bluff en tablero favorable — disparar ✓
  {id:1510,type:"vbet",hand:"J♦T♦",board:"8♠9♣A♥7♠2♦",street:"river",open:true,size:"large",bluff:true,ctx:"bluff_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 8♠9♣A♥: BB checkea. Hero apuesta 3.5BB (J-T tiene gutshot + backdoor flush). BB paga. Bote: 12.5BB.\nTurn 7♠: BB checkea. Hero apuesta 8BB (open-ender al J/6, dos picas en tablero). BB paga. Bote: 28.5BB.\nRiver 2♦: BB checkea. Hero actúa (JT no hizo el straight ni el flush — As alto).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 8♠9♣A♥: BB checks. Hero bets 3.5BB (J-T has gutshot + backdoor flush). BB calls. Pot: 12.5BB.\nTurn 7♠: BB checks. Hero bets 8BB (open-ender to J/6, two spades on board). BB calls. Pot: 28.5BB.\nRiver 2♦: BB checks. Hero acts (JT missed the straight and flush — Ace-high).",
   en:"BET (BLUFF). JT missed but the river 2♦ is a blank — it doesn't improve BB's most likely hands (which called for their piece of the 8-9-A-7 board: AT, A8, 89, 78). Your story of 3-barreling on an 8-9-A-7 board STRONGLY represents AX hands (the BTN opening range has lots of AK, AQ, AJ, AT). BB's calling range has a lot of floated hands and medium pairs that must fold vs the third barrel. Fire.",
   es:"APOSTAR (FAROL). JT falló pero el 2♦ del river es una blank — no mejora las manos más probables del BB (que pagó por su conexión con 8-9-A-7: AT, A8, 89, 78). Tu historia de 3 barrels en un tablero 8-9-A-7 REPRESENTA FUERTEMENTE manos AX (el rango de apertura del BTN tiene mucho AK, AQ, AJ, AT). El rango de pago del BB tiene muchas manos flotadas y pares medios que deben foldear vs el tercer barrel. Dispara."},

  // 1511: River bluff vs calling station — checkear ✓
  {id:1511,type:"vbet",hand:"K♣Q♣",board:"J♠T♦6♥3♣A♠",street:"river",open:false,size:null,bluff:true,ctx:"bluff_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Fish calling station (VPIP 58%, WTSD 44%, WSD llamante frecuente)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop J♠T♦6♥: BB checkea. Hero apuesta 3.5BB (K-Q tiene gutshot al As, dos overcards). BB paga. Bote: 12.5BB.\nTurn 3♣: BB checkea. Hero apuesta 8BB (representando valor). BB paga. Bote: 28.5BB.\nRiver A♠: BB checkea. Hero actúa (KQ consiguió el straight al rey con A-K-Q-J-T!).",
   descEn:"NL25 · CO vs BB · Calling station fish (VPIP 58%, WTSD 44%, frequent showdown caller)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop J♠T♦6♥: BB checks. Hero bets 3.5BB (K-Q has gutshot to Ace, two overcards). BB calls. Pot: 12.5BB.\nTurn 3♣: BB checks. Hero bets 8BB (representing value). BB calls. Pot: 28.5BB.\nRiver A♠: BB checks. Hero acts (KQ made the King-high straight A-K-Q-J-T!).",
   es:"Ojo: esta situación tiene trampa. KQ con A♠ en el river HIZO el straight al rey (A-K-Q-J-T). Pero la decisión no es 'bet o check como farol' sino 'bet de valor o check'. El fish (WTSD 44%) llama muchas river bets — apostar como valor con el straight es claramente +EV. Sin embargo, la 'trampa' del ejercicio es reconocer que no es una decisión de farol: ¡es valor! Apuesta para extraer valor del fish.",
   en:"Note: this situation has a twist. KQ with A♠ on the river MADE the King-high straight (A-K-Q-J-T). But the decision isn't 'bluff bet or check' — it's 'value bet or check'. The fish (WTSD 44%) calls many river bets — betting for value with the straight is clearly +EV. The 'trap' of this exercise is recognizing it's not a bluff decision: it's value! Bet to extract value from the fish."},

  // 1512: River triple barrel vs reg — precio correcto, fold equity alta — disparar ✓
  {id:1512,type:"vbet",hand:"A♣5♣",board:"K♦9♣6♥2♠T♠",street:"river",open:true,size:"large",bluff:true,ctx:"bluff_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular sólido (VPIP 22%, PFR 17%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop K♦9♣6♥: BB checkea. Hero apuesta 3.5BB (proyecto de trébol + backdoor). BB paga. Bote: 12.5BB.\nTurn 2♠: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver T♠: BB checkea. Hero actúa (A5s missed, As alto).",
   descEn:"NL25 · BTN vs BB · Solid regular (VPIP 22%, PFR 17%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop K♦9♣6♥: BB checks. Hero bets 3.5BB (club draw + backdoor). BB calls. Pot: 12.5BB.\nTurn 2♠: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver T♠: BB checks. Hero acts (A5s missed, Ace-high).",
   es:"APOSTAR (FAROL). A5s falló pero el T♠ del river es una carta difícil para el BB que pagó en tablero K-9-6-2 — el rango de pago de la BB en el flop tiene mucha media pareja (77-TT), KX débil (K8-K6), y algo de 9X. El T♠ 'limpia' el tablero para la historia del BTN (que representa AK, KK, AA, KT, TT). La fold equity vs un regular en 3 barrels es suficiente. Dispara.",
   en:"BET (BLUFF). A5s missed but the T♠ river is a tough card for BB who called on K-9-6-2 — BB's flop calling range has lots of medium pairs (77-TT), weak KX (K8-K6), and some 9X. The T♠ 'cleans up' the board for BTN's story (representing AK, KK, AA, KT, TT). Fold equity vs a regular on 3 barrels is sufficient. Fire."},

  // 1513: River con mano de showdown — no farolear ✓
  {id:1513,type:"vbet",hand:"T♥T♦",board:"9♠7♣2♥4♦6♠",street:"river",open:false,size:null,bluff:true,ctx:"bluff_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 9♠7♣2♥: BB checkea. Hero apuesta 3.5BB (TT como overpair). BB paga. Bote: 12.5BB.\nTurn 4♦: BB checkea. Hero apuesta 8BB (overpair, algunas manos del BB tienen draws). BB paga. Bote: 28.5BB.\nRiver 6♠: BB checkea. Hero actúa (TT: overpair en tablero 9-7-6-4-2 con straight completo).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 9♠7♣2♥: BB checks. Hero bets 3.5BB (TT as overpair). BB calls. Pot: 12.5BB.\nTurn 4♦: BB checks. Hero bets 8BB (overpair, some BB hands have draws). BB calls. Pot: 28.5BB.\nRiver 6♠: BB checks. Hero acts (TT: overpair on 9-7-6-4-2 board with completed straight).",
   es:"CHECKEAR. TT como overpair en river 9♠7♣2♥4♦6♠ — el tablero completa el straight 5-6-7-8-9 (con 5, 8 o T cualquiera puede tener straight). Lo peor: el 6♠ trae el straight 4-5-6-7-8 o 5-6-7-8-9. TT tiene showdown value como bluff-catcher (gana al showdown vs manos mediocres) pero apostar aquí solo extrae calls de manos mejores que TT (8X, straight) y fold de manos peores. Checkea y ve al showdown.",
   en:"CHECK. TT as an overpair on river 9♠7♣2♥4♦6♠ — the board completes the 5-6-7-8-9 straight (with 5, 8, or T anyone can have the straight). Worst case: the 6♠ brings the 4-5-6-7-8 or 5-6-7-8-9 straight. TT has showdown value as a bluff-catcher (wins at showdown vs mediocre hands) but betting here only gets calls from hands better than TT (8X, straight) and folds from worse hands. Check and go to showdown."},

  // 1514: River con bloqueadores al straight — disparar ✓
  {id:1514,type:"vbet",hand:"A♠K♠",board:"Q♦J♣T♥4♠9♦",street:"river",open:true,size:"large",bluff:true,ctx:"bluff_river",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Regular balanceado (VPIP 24%, PFR 18%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♦J♣T♥: BB checkea. Hero apuesta 3.5BB (AK tiene gutshot al 9 + backdoor flush). BB paga. Bote: 12.5BB.\nTurn 4♠: BB checkea. Hero apuesta 8BB. BB paga. Bote: 28.5BB.\nRiver 9♦: BB checkea. Hero actúa (AK falló el straight, pero bloquea A-K-Q-J-T).",
   descEn:"NL25 · CO vs BB · Balanced regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♦J♣T♥: BB checks. Hero bets 3.5BB (AK has gutshot to 9 + backdoor flush). BB calls. Pot: 12.5BB.\nTurn 4♠: BB checks. Hero bets 8BB. BB calls. Pot: 28.5BB.\nRiver 9♦: BB checks. Hero acts (AK missed the straight, but blocks A-K-Q-J-T).",
   es:"APOSTAR (FAROL). AK tiene bloqueadores excelentes para este river: bloquea las combos K-Q-J-T que forman el straight regio (que el BB podría tener para justificar llamar). El 9♦ completa el straight 9-T-J-Q-K (que TOCA AK). Tu rango de 3 barrels en Q-J-T-4-9 representa fuertemente KX con straightes. El BB tiene muchas manos de pago mediocres en su rango que deben foldear. Dispara.",
   en:"BET (BLUFF). AK has excellent blockers for this river: it blocks the K-Q-J-T combos that form the royal straight (which BB might have to justify calling). The 9♦ completes the 9-T-J-Q-K straight (which AK HITS). Your 3-barrel range on Q-J-T-4-9 strongly represents KX with straights. BB has many mediocre calling hands in their range that must fold. Fire."},

  // 1515: River farol demasiado obvio — checkear ✓
  {id:1515,type:"vbet",hand:"8♣7♣",board:"9♦T♥5♣6♠2♥",street:"river",open:false,size:null,bluff:true,ctx:"bluff_river",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 9♦T♥5♣: BB checkea. Hero apuesta 3.5BB (87s: open-ender a J o 6). BB paga. Bote: 12.5BB.\nTurn 6♠: BB checkea. Hero apuesta 8BB (87s completa el straight con 6-7-8-9-T!). BB paga. Bote: 28.5BB.\nRiver 2♥: BB checkea. Hero actúa (87s tiene straight 6-7-8-9-T).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 9♦T♥5♣: BB checks. Hero bets 3.5BB (87s: open-ended to J or 6). BB calls. Pot: 12.5BB.\nTurn 6♠: BB checks. Hero bets 8BB (87s completes the straight with 6-7-8-9-T!). BB calls. Pot: 28.5BB.\nRiver 2♥: BB checks. Hero acts (87s has straight 6-7-8-9-T).",
   es:"Ojo: otra trampa. 87s con el 6♠ del turn HIZO el straight 6-7-8-9-T. En el river, la decisión no es 'farol o check' sino 'apostar valor o checkear'. Con un straight, bet para extraer valor. El 2♥ del river es una blank que no mejora el rango del BB. Apostar por valor con el straight es la jugada óptima — el BB puede pagar con TX, 9X o cualquier mano que creyó buena. ¡Apuesta el valor!",
   en:"Note: another trap. 87s with the 6♠ turn MADE the straight 6-7-8-9-T. On the river, the decision isn't 'bluff or check' — it's 'bet for value or check'. With a straight, bet to extract value. The 2♥ river is a blank that doesn't improve BB's range. Betting for value with the straight is the optimal play — BB may call with TX, 9X or any hand they thought was good. Bet for value!"},

  // ── C-BET RETRASADA (DELAYED C-BET) — Turn (3) ───────────────────────────────
  // Hero checkeó el flop (no c-beteó); ambos checkean; decide en el turn

  // 1516: C-bet retrasada con equity — disparar en turn ✓
  {id:1516,type:"vbet",hand:"K♦Q♦",board:"J♣8♣4♥T♦",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_delayed",pos:"CO",callPos:"BB",
   descEs:"NL25 · CO vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre CO 2.5BB. BB paga. Bote: 5.5BB.\nFlop J♣8♣4♥: BB checkea. Hero CHECKEA (no c-betea). BB checkea. Bote: 5.5BB.\nTurn T♦: BB checkea. Hero actúa (KQ tiene gutshot al 9 o As para el straight, + dos overcards).",
   descEn:"NL25 · CO vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens CO 2.5BB. BB calls. Pot: 5.5BB.\nFlop J♣8♣4♥: BB checks. Hero CHECKS (doesn't c-bet). BB checks. Pot: 5.5BB.\nTurn T♦: BB checks. Hero acts (KQ has gutshot to 9 or Ace for straight, + two overcards).",
   es:"APOSTAR (C-BET RETRASADA). KQ mejora en el turn T♦ — ahora tiene gutshot al 9 para el straight (8-9-T-J-Q) o el 9 para (9-T-J-Q-K). La carta T también favorece el rango del CO que abrió preflop (representa mucho KX, QX, JX, TX). Disparar ahora como c-bet retrasada con equity real (gutshot + dos overcards = ≈10 outs) es la línea correcta.",
   en:"BET (DELAYED C-BET). KQ improves on the T♦ turn — now has gutshot to 9 for the straight (8-9-T-J-Q) or 9 for (9-T-J-Q-K). The T card also favors CO's opening range (represents lots of KX, QX, JX, TX). Firing now as a delayed c-bet with real equity (gutshot + two overcards = ≈10 outs) is the correct line."},

  // 1517: C-bet retrasada en blank — checkear ✓
  {id:1517,type:"vbet",hand:"A♣6♠",board:"Q♦J♣T♥2♦",street:"turn",open:false,size:null,bluff:true,ctx:"bluff_delayed",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop Q♦J♣T♥: BB checkea. Hero CHECKEA (flop peligroso, manos conectadas del BB). BB checkea. Bote: 5.5BB.\nTurn 2♦: BB checkea. Hero actúa (A6o tiene As overcard, sin equity real en tablero Q-J-T-2).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop Q♦J♣T♥: BB checks. Hero CHECKS (dangerous flop, BB's connected hands). BB checks. Pot: 5.5BB.\nTurn 2♦: BB checks. Hero acts (A6o has Ace overcard, no real equity on Q-J-T-2 board).",
   es:"CHECKEAR. A6o sin equity en Q-J-T-2: el tablero Q-J-T favorece masivamente el rango del BB (que tiene muchos QX, JX, TX, KX, 89, K9). Una c-bet retrasada sin equity y en un tablero peligroso para tu rango tiene EV negativo — el BB no foldea suficiente con manos que conectan con Q-J-T. Checkea y evalúa el river.",
   en:"CHECK. A6o with no equity on Q-J-T-2: the Q-J-T board massively favors BB's range (which has lots of QX, JX, TX, KX, 89, K9). A delayed c-bet without equity on a board dangerous for your range has negative EV — BB doesn't fold enough with hands connecting to Q-J-T. Check and evaluate the river."},

  // 1518: C-bet retrasada — el turn cambia la historia favorablemente — disparar ✓
  {id:1518,type:"vbet",hand:"A♠T♠",board:"7♦4♣2♥K♠",street:"turn",open:true,size:"large",bluff:true,ctx:"bluff_delayed",pos:"BTN",callPos:"BB",
   descEs:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero abre BTN 2.5BB. BB paga. Bote: 5.5BB.\nFlop 7♦4♣2♥: BB checkea. Hero CHECKEA (tablero bajo, no le pega al rango del BTN tan claramente). BB checkea. Bote: 5.5BB.\nTurn K♠: BB checkea. Hero actúa (AT tiene As + backdoor flush de picas, y el K es una carta de turn ideal para el BTN).",
   descEn:"NL25 · BTN vs BB · Regular (VPIP 24%, PFR 18%)\nPreflop: Hero opens BTN 2.5BB. BB calls. Pot: 5.5BB.\nFlop 7♦4♣2♥: BB checks. Hero CHECKS (low board, doesn't connect so clearly to BTN's range). BB checks. Pot: 5.5BB.\nTurn K♠: BB checks. Hero acts (AT has Ace + backdoor spade flush, and K is an ideal turn card for BTN).",
   es:"APOSTAR (C-BET RETRASADA). El K♠ del turn es una carta excelente para el BTN — el rango del BTN que abrió tiene mucho AK, KQ, KJ que el BB no puede balancear bien. AT también mejora (gutshot a J o Q para el straight, overcard As). Disparar la c-bet retrasada en el turn K con AT (que representa bien manos de valor) es la jugada correcta — fold equity alta y equity propia suficiente.",
   en:"BET (DELAYED C-BET). The K♠ on the turn is an excellent card for BTN — BTN's opening range has lots of AK, KQ, KJ that BB can't balance well. AT also improves (gutshot to J or Q for the straight, Ace overcard). Firing the delayed c-bet on the K turn with AT (which well represents value hands) is the correct play — high fold equity and sufficient own equity."},

  // ── RAISE COMO FAROL / BLUFF RAISE (2) ───────────────────────────────────────

  // 1519: Bluff-raise en flop con draw + fold equity — levantar ✓
  {id:1519,type:"vbet",hand:"8♦7♦",board:"9♠T♣2♦",street:"flop",open:true,size:"large",bluff:true,ctx:"bluff_raise",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Regular (VPIP 26%, PFR 20%)\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop 9♠T♣2♦: Hero checkea. BTN apuesta 3.5BB (c-bet 63%). Hero actúa (87s: open-ended straight draw J o 6, 8 outs).",
   descEn:"NL25 · BB vs BTN · Regular (VPIP 26%, PFR 20%)\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop 9♠T♣2♦: Hero checks. BTN bets 3.5BB (c-bet 63%). Hero acts (87s: open-ended straight draw J or 6, 8 outs).",
   es:"RAISE COMO FAROL (BLUFF-RAISE). 87s tiene 8 outs para el straight (cualquier J o 6) = ≈36% de equity a dos calles. Hacerle un raise como farol al BTN en este flop tiene sentido: 1) equity alta si te pagan, 2) fold equity real — el BTN c-beteó manos débiles que foldean, 3) tu rango en el BB puede tener 9X, TX legítimamente. El raise semi-bluff con draw es la jugada más agresiva y +EV aquí.",
   en:"RAISE (BLUFF-RAISE). 87s has 8 outs to the straight (any J or 6) = ≈36% equity over two streets. Raising as a bluff vs BTN's flop c-bet makes sense: 1) high equity if called, 2) real fold equity — BTN c-bet weak hands that will fold, 3) your BB range can legitimately have 9X, TX. The semi-bluff raise with a draw is the most aggressive and +EV play here."},

  // 1520: Bluff-raise sin equity ni representación — checkear o pagar ✓
  {id:1520,type:"vbet",hand:"A♣3♣",board:"K♠Q♦J♠",street:"flop",open:false,size:null,bluff:true,ctx:"bluff_raise",pos:"BB",callPos:"BTN",
   descEs:"NL25 · BB vs BTN · Regular agresivo (VPIP 30%, PFR 24%, CBet Flop 75%)\nPreflop: BTN abre 2.5BB. Hero BB paga. Bote: 5.5BB.\nFlop K♠Q♦J♠: Hero checkea. BTN apuesta 3.5BB. Hero actúa (A3s tiene As overcard pero sin equity directa real en K-Q-J).",
   descEn:"NL25 · BB vs BTN · Aggressive regular (VPIP 30%, PFR 24%, CBet Flop 75%)\nPreflop: BTN opens 2.5BB. Hero BB calls. Pot: 5.5BB.\nFlop K♠Q♦J♠: Hero checks. BTN bets 3.5BB. Hero acts (A3s has Ace overcard but no real direct equity on K-Q-J).",
   es:"CHECKEAR / PAGAR (no hacer el raise). A3s en K-Q-J: el tablero K♠Q♦J♠ favorece masivamente el rango del BTN (que tiene AK, AJ, KQ, KJ, QJ, TT+). Hacer un bluff-raise aquí sería un error grave: 1) sin equity real (A alto no llega a nada), 2) sin fold equity suficiente (el BTN no tiene muchas manos débiles que foldeen a este c-bet en K-Q-J), 3) el raise-farol te expone a un re-raise del BTN que tendrá muchas manos fuertes. Check-fold es el jugada óptima.",
   en:"CHECK / CALL (don't raise). A3s on K-Q-J: the K♠Q♦J♠ board massively favors BTN's range (which has AK, AJ, KQ, KJ, QJ, TT+). Bluff-raising here would be a major mistake: 1) no real equity (Ace-high goes nowhere), 2) insufficient fold equity (BTN doesn't have many weak hands that would fold this c-bet on K-Q-J), 3) the bluff-raise exposes you to a re-raise from BTN who will have many strong hands. Check-fold is the optimal play."},

];
